### PR TITLE
Load JQuery over HTTPS.

### PR DESCRIPTION
**Pull request by nunohumberto**
Page is broken when using HTTPS due to loading JQuery over HTTP.

### CODE REVIEW

**Comment by nmssilva** [comment]
what do @alagoa 🤔🤔🤔

**Comment by nmssilva** [comment]
@nunohumberto still broken but fixed a bug tho 😂👌

**Comment by alagoa** [comment]
lmao I told you to fix it before merging to _master_, not after @nmssilva

**Comment by nmssilva** [comment]
ite ok bc ite not br0k3n now 😄

**Pull request merged**
